### ISSUE TITLE
Timeout seems to be ignored on Android

### ISSUE THREAD

**Issue by digital-synapse** [alexrainman/ModernHttpClient#4]
httpClient.Timeout = msTimeout == -1 ? defaultTimeout : TimeSpan.FromMilliseconds(msTimeout);

//...

using (webResponse = await httpClient.SendAsync(request, cancellationToken).ConfigureAwait(false))

// Timeout was ignored. if placing a breakpoint in OkHttpNetworkHandler.cs you can see that Timeout is actually null somehow even though it was previously set.

**Comment by digital-synapse** [comment]
Ahh i see, Somehow setting httpClient.Timeout worked with the original ModernHttpClient. As you say, setting on the handler instead solves the issue. Thank you!

**Comment by alexrainman** [comment]
Android or iOS?

**Comment by Johnderate** [comment]
This is on Android. The 10 seconds are the standard timeout from okhttp3 I presume.

**Comment by alexrainman** [comment]
I will try to reproduce this.

**Comment by adrianknight89** [comment]
I set the timeout on NativeMessageHandler to 30 secs, and it seems to be working on Android for me.

**Comment by Johnderate** [comment]
@adrianknight89 Are you doing anything differently than I am in my example above? (I know its quite a mouthful)

**Comment by adrianknight89** [comment]
@Johnderate In my case, I have a single static instance of `HttpClient` that gets used across the application, and I'm also not setting anything on `NativeMessageHandler` other than `Timeout`. I know this is not good practice, but I've defaulted every API to be POST (hence I'm invoking PostAsync instead of SendAsync on the client). You should see if you're having your timeout issues with GET requests or all HTTP methods. 

Make sure to update your Nuget packages. I'm also using `client.DefaultRequestHeaders.Authorization`. Finally, I'm not building an `HttpRequestMessage`. Things like `CultureInfo` can be passed as an API parameter.

**Comment by alexrainman** [comment]
Using a static instance of HttpClient is the right way to do it, otherwise you won't be reusing sockets. I have tried to reproduce this without luck.

**Comment by syahman** [comment]
> NativeMessageHandler

how to set it ?
