### ISSUE TITLE
Version Conflict for Xamarin.GooglePlayServices.Basement for apps that use GooglePlayServices.Ads

### ISSUE THREAD

**Issue by mzhukovs** [alexrainman/ModernHttpClient#56]
NU1107: Version conflict detected for Xamarin.GooglePlayServices.Basement. Install/reference Xamarin.GooglePlayServices.Basement 71.1620.0 directly to project MyProject.Droid to resolve this issue. 

 MyProject.Droid -> Xamarin.GooglePlayServices.Ads.Lite 71.1712.1 -> Xamarin.GooglePlayServices.Basement (>= 71.1620.0) 
 MyProject.Droid -> modernhttpclient-updated 3.4.1 -> Xamarin.GooglePlayServices.SafetyNet 60.1142.1 -> Xamarin.GooglePlayServices.Basement (= 60.1142.1).

**Comment by jded76** [comment]
I'm experiencing difficulties with that too. 
I don't use any of the Google Services on my project, so I don't know if I want to install the new dependencies of ModernHttpClient (I show them from latest commit). 
Anyway as it is now I cannot even install them because of the version conflict.

I also have another problem and I think it is related to this.
After latest version there is a call to Google Play services (ProviderInstaller). 
I have an android 4.4 emulator without Google Play Services installed and I cannot work on that emulator any more.

I think all of these changes made to support TLS 1.2 on old android versions. 

Maybe it's a better idea to call the ProviderInstaller after a failure of TLS handshake, otherwise on every new connection (or instance of moderHttpClient) a call to ProviderInstaller is made, and if the device is already updated that call does nothing. 
IMO the application is responsible for this and not the communication library. The application can call it once when it starts or after a TLS failure for example.

Anyway thanks to alexrainman for his work to this library.

**Comment by alexrainman** [comment]
I am going to remove that dependency and provide it as a workaround instead. I wasn’t so convinced of it anyway.

**Comment by alexrainman** [comment]
Version 3.4.2 is out.
